const SalarianBlog = () => {
    return (
        <div>
            <header>
                <h1><a target="_blank" title="View actual post on Mass Effect website" className="text-primary hover:text-onPrimaryBg" href="https://masseffect.fandom.com/wiki/Salarian">Salarian</a></h1>
            </header>
            <div>
                <div>
                    <div className="float-right">
                        <a title="Salarian bartender in the Citadel" href="/src//img/foreground/Codex_ME_-_Salarians.webp">
                            <img alt="Salarian bartender in the Citadel" src="/src/img/foreground/Codex_ME_-_Salarians.webp" width={400} />
                        </a>
                    </div>
                    <p>The second species to join the Citadel, the salarians are warm-blooded amphibians native to the planet Sur'Kesh. Salarians possess a hyperactive metabolism; they think fast, talk fast, and move fast. To salarians, other species seem sluggish and dull-witted, especially the elcor. Unfortunately, their metabolic speed leaves them with a relatively short lifespan; salarians over the age of 40 are a rarity.</p>
                    <p>Salarians are known for their observational capability and non-linear thinking. This manifests as an aptitude for research and espionage. They are constantly experimenting and inventing, and it is generally accepted that they always know more than they are letting on.</p>
                </div>
            </div>
            <br/>
            <div>
                <h1>Biology</h1>
                <p>The salarians are a bipedal race of amphibians, with tall, elongated bodies well-suited for their high metabolism, and skeletons composed of more cartilage than those of other races such as humans. Salarian heads are long and thin, and have a pair of horns protruding from the top of their skulls. Skin varies in color, from bright reds and greens to the more common shades of blue or grey. Their blood is a greenish color. Salarians are androgynous, and exhibit no major facial differences between males and females.</p>
                <p>Salarian eyes are large and oval and have thin membranes in place of eyelids. The pupils are a wide slit, oriented horizontally, and the irises can be dark green, purple, red, blue, or brown. Salarians can see ultraviolet at the short-wavelength end of the spectrum. Salarians blink upwards, rather than downwards as humans do. When salarians roll their eyes, it is not a sign of disdain as with humans, but rather a response to situations where the thin protective membranes require extra help in defending against dryness or irritants.</p>
                <p>Salarians are noted for their high-speed metabolism, which allows them to function on just one hour of sleep a day. Their minds and bodies work faster than most sapient races, making them seem restless or hyperactive. The drawback of this active metabolism is a short lifespan of around 40 human years.</p>
                <p>The salarians are amphibian haplo-diploid egg-layers; unfertilized eggs produce males and fertilized eggs produce females. Once a year, a salarian female will lay a clutch of dozens of eggs. Social rules prevent all but a fraction from being fertilized. As a result, 90% of the species is male.</p>
                <p>Salarians have photographic memories and rarely forget a fact. They also possess a form of psychological "imprinting", tending to defer to those they knew in their youth. Salarian hatching is a solemn ritual in which the clan matriarch, known as the Dalatrass, isolates herself with the eggs. The young salarians psychologically imprint on her and tend to defer to her wishes. During the hatching of daughters, the Dalatrasses of the mother and father’s clans are present at the imprinting. This ensures the offspring have equal loyalty to both, ensuring the desired dynastic and political unity.</p>
                <p>Salarian sex drive and reproduction differ from that of humans, with Mordin Solus claiming that it is not hormone-based. Reproduction is more of a necessity and salarians do not seem to desire sex for pleasure. They are, however, attracted to the asari, and one salarian notes that "even humans find the Consort irresistible."</p>
            </div>
            <br/>
            <div>
                <h1>History</h1>
                <p>Salarians were already thriving on Sur'Kesh 50,000 years before the modern age, albeit in a thoroughly primitive state. According to Javik, the salarians of his time were classified as "lizard people". They used to eat flies, licked their eyes, and their body parts were considered delicacies by the Protheans. In addition to livers, salarian kidneys were apparently best served at room temperature, preferably with the salarian still alive, as its fear adds "spice".</p>
                <p>Eventually, they progressed technologically to the point of colonizing planets beyond their own.</p>
                <p>On their first three interstellar colonies, the salarians planted settlements named Aegohr, Mannovai, and Jaëto. According to Kirrahe, those settlements "remain at the heart of salarian territory to this day".</p>
                <p>In what became known as the Tecunis Expedition, the salarians discovered the Citadel only a few decades after the asari, making them only the second species to do so since the Prothean extinction. They opened diplomatic relations with the asari at once and became one of the founding species of the Citadel Council. In a gesture of trust, the salarians opened the records of one of their intelligence services, the League of One, but this quickly created problems when the League's members found themselves in danger as a result. The League slaughtered the entire Union inner cabinet, but were later hunted down, leaving only relics behind.</p>
                <p>The salarians also played a significant role in the advancement of the krogan species. The salarians provided the krogan with advanced technology and a new, tranquil home planet (in order to manipulate the krogan into eradicating the rachni for the Council). The peaceful home planet and better technology put less strain on the krogan as a species; they no longer had to worry about simply surviving on a dangerous planet with primitive technology, as they did before contact with the salarians. This comparatively easy life, combined with their exceedingly high birth rate, allowed the krogan the time, numbers, and energy to spread through Citadel space, aggressively claiming formerly allied planets as their own. In order to end these "Krogan Rebellions," the salarians then provided the turians with the genophage, a biological weapon that effectively sterilized the krogan, resulting in almost all krogan pregnancies ending in stillbirth.</p>
                <p>Though their military is nothing special, salarians are currently seen as the premier intelligence and information-gathering arm of the Council. As such, they are well respected, but some races, including a few humans, see the salarians as manipulators.</p>
            </div>
            <br/>
            <div>
                <h1>Culture</h1>
                <p>Salarians excel at invention, preferring to use cutting-edge technology rather than settle for anything less. For example, their GARDIAN starship defenses put emphasis on high performance over reliability even though a malfunction could cost lives. Even Schells rejected a cheating device that used "brute force," spending five years to refine it into a more sophisticated, undetectable system.</p>
                <p>The salarians see information gathering and even spying as a matter of course when dealing with other races, but to them this is not underhanded: they simply embrace the dictum of "knowledge is power". Alliance counterintelligence agencies are constantly uncovering salarian agents and cyber-warfare incursions, but there is little they can do to stop them. As a salarian information broker once told David Anderson, "Your species has been transmitting data across the extranet for less than a decade. My species has been directing the primary espionage and intelligence operations for the Council for two thousand years."</p>
                <p>Normally, the rare salarian females are cloistered on their worlds out of tradition and respect. Powerful female Dalatrasses are dynasts and political kingpins. They determine the political course of their respective regions through shrewd negotiation. Though male salarians rise to positions of great authority in business, academia, or the military, they rarely have any input on politics; one notable exception to this rule is Valern, a male salarian representing his race on the Citadel Council in 2183.</p>
                <p>Due to their method of reproduction, salarians have no concept of romantic love, sexual attraction, or the biological impulses and social rituals that complicate other species' lives. Male-female relationships are rare (due to the scarcity of females) and more akin to human friendship. Sexuality is strictly for the purpose of reproduction. Ancient social codes determine who gets to fertilize eggs, which produces more daughters to continue the bloodline. Fertilization generally only occurs after months of negotiation between the parents' clans, and is done for purposes of political and dynastic alliance. No salarian would imagine defying this code.</p>
                <p>Salarian names are quite complex. A full name includes – in order – the name of a salarian's homeworld, nation, city, district, clan name and given name. For example, a salarian named Gorot II Heranon Mal Dinest Got Inoste Ledra would be called either by his clan name, Inoste, or his given name, Ledra.</p>
                <p>The salarian race also includes the Lystheni "offshoot." How the Lystheni are distinct from mainline salarians and why they are currently unwelcome in Council space is unrevealed. Lystheni salarians may be found living among batarians, exiled quarians, and other galactic refuse at Omega.</p>
                <p>Salarians celebrate "Betau," the first day of their New Year. Traditionally, it marks the end of winter in the southern hemisphere on the salarian homeworld, Sur'Kesh. During this occasion, they repay debts, and petition favors from one another.</p>
                <p>When it comes to keeping secrets, salarians have two types of social cues. The first type is personal or guilt-based, and invites suspicion and exploration. The second type is for secrets deemed dangerous if discovered, and signals discourage curiosity for protection of the relevant parties. Reflexive body language conveys the type of secret and cannot be faked convincingly; an analogue is that of a human faking a yawn.</p>
                <h3>Economy</h3>
                <p>The salarian economy is the smallest of the three Council races, but still far larger than the Alliance. It is based on "bleeding-edge" technologies; salarian industries are leaders in most fields. They make up for a lack of military quantity by holding a decisive superiority in quality.</p>
                <h3>Religion</h3>
                <p>While modern Salarians are not notably religious, in ancient times some salarians practiced a religion that featured the so-called "stones of life"; Mosiiba, Mosiino and Mosiives. Some faiths survive however; one of the less favored salarian religions (which the Council deems a "cult") worships a goddess, and claims that a certain pattern of overlapping craters in the southern hemisphere of Trelyn resembles her. Liara T'Soni comments that many salarians believe in a wheel of life, which Mordin Solus likens to Hinduism due to a shared belief in reincarnation.</p>
            </div>
            <br/>
            <div>
                <h1>Government</h1>
                <p>The salarian government, since at least the formation of the Council in 500 BCE, is called the Salarian Union. It is a labyrinthine web of matrilineal bloodlines, with political alliances formed through interbreeding.</p>
                <p>In many ways, the salarian political network functions like the noble families of Earth’s Medieval Europe. Structurally, the government consists of fiefdoms, baronies, duchies, planets, and marches (colonization clusters). These are human nicknames, as the original salarian is unpronounceable. Each area is ruled by a single Dalatrass (matriarchal head-of-household) and represents an increasing amount of territory and prestige within the salarian political web.</p>
                <p>Approaching 100 members, the first circle of a salarian's clan comprises parents, siblings, uncles, aunts, and cousins. The next circle includes second cousins, etc., and escalates to well over 1000 members. The fourth or fifth circle of a clan numbers into the millions. Salarian loyalty is greatest to their first circle and diminishes from there. Their photographic memories allow salarians to recognize all their myriad relatives.</p>
            </div>
            <div>
                <h1>Military</h1>
                <p>In principle, the salarian military is similar to the Systems Alliance, a small volunteer army that focuses on maneuver warfare. What differentiates the salarians is not their equipment or doctrine, but their intelligence services and rules of engagement. The salarians believe that a war should be won before it begins (a doctrine also espoused by some of humanity's greatest generals, such as Sun Tzu).</p>
                <p>The unquestioned superiority of their intelligence services allows them to use their small military to maximum effectiveness. Well before fighting breaks out, they possess complete knowledge of their enemy's positions, intentions, and timetable. Their powerful intelligence network is spearheaded in the field by the Special Tasks Group (STG), which is responsible for monitoring developing situations and taking necessary action, usually without the shackles of traditional laws and procedures. This may be as simple as scouting and information gathering, or as complex as ensuring a conveniently unstable political situation stays that way. The effectiveness of the STG during the Krogan Rebellion is what provided the template for the Council to establish their Spectre program immediately afterward.</p>
                <p>In every war the salarians have fought, they struck first and without warning. For the salarians, to know an enemy plans to attack and let it happen is folly; to announce their own plans to attack is insanity. They find the human moral concepts of "do not fire until fired upon" and "declare a war before prosecuting it" incredibly naive. In defensive wars, they execute devastating preemptive strikes hours before the enemy's own attacks. On the offense, they have never issued an official declaration of war before attacking.</p>
                <p>Biotics are virtually unknown in the salarian military. Those with such abilities are considered too valuable to be used as cannon fodder and are assigned to the intelligence services.</p>
                <p>While capable of defending themselves against most threats, the salarians know that they are small fish in a universe filled with sharks. As a point of survival, they have cultivated strong alliances with larger powers, particularly with the turians. Though the relationship between the two species was rocky at first due to the krogan uplift fiasco, the salarians take pains to keep this relationship strong enough that anyone who might threaten them risks turian intervention.</p>
                <p>The salarian navy has sixteen dreadnoughts, which is considerably less than the maximum they are allowed to build under the Treaty of Farixen. This slowdown in dreadnought production was a consequence of the increasing complexity of the salarians' designs. After covertly obtaining and researching stealth technology used by the SSV Normandy and Normandy SR-2, the salarians were able to produce dreadnoughts with stealth capabilities, a previously unthinkable feat. Salarian dedication to adopting bleeding-edge technology is also demonstrated by their ships' costly armament. Warships are equipped with the latest GARDIAN defense systems and utilize ultraviolet antiship lasers, which are more expensive and energy demanding than standard infrared lasers, but more effective. Even salarian scouting flotillas are armed with hull-mounted Thanix cannons.</p>
                <p>Salarian STG units are equipped with a variety of extremely high tech weaponry including the Scorpion, a pistol capable of firing high explosive "sticky projectiles", and the Venom, a shotgun capable of firing micro-grenades. The salarian military also fields the A-61 Mantis Gunship.</p>
            </div>
        </div>
    );
}
 
export default SalarianBlog;