const TurianBlog = () => {
    return (
        <div>
            <header>
                <h1><a target="_blank" title="View actual post on Mass Effect website" className="text-primary hover:text-onPrimaryBg" href="https://masseffect.fandom.com/wiki/Turian">Turian</a></h1>
            </header>
            <div>
                <div>
                    <div className="float-right">
                        <a title="A turian in profile" href="/src/img/foreground/Codex_ME_-_Turians.webp">
                            <img alt="A turian in profile" src="/src/img/foreground/Codex_ME_-_Turians.webp" width={400} />
                        </a>
                    </div>
                    <p>Known for their militaristic and disciplined culture, the turians were the third race to join the Citadel Council. They gained their Council seat after defeating the hostile krogan for the Council during the Krogan Rebellions. The turians deployed a salarian-created biological weapon called the genophage, which virtually sterilised the krogan and sent them into a decline. The turians then filled the peacekeeping niche left by the once-cooperative krogan, and eventually gained a Council seat in recognition of their efforts.</p>
                    <p>Originally from the planet Palaven, turians are best known for their military role, particularly their contributions of soldiers and starships to the Citadel Fleet. They are respected for their public service ethic—it was the turians who first proposed creating C-Sec—but are sometimes seen as imperialist or rigid by other races. There is some animosity between turians and humans, largely due to the turian role in the First Contact War. This bitterness is slowly beginning to heal—as shown by the cooperation of the two races on the construction of the SSV Normandy—but many turians still resent humans, and vice versa.</p>
                </div>
            </div>
            <br/>
            <div>
                <h1>Biology</h1>
                <p>Turians typically stand over six feet tall [1.8m], have two long, proportionately thick fingers and an opposable thumb on each hand, each tipped with talons, and a set of mandibles around their mouths. The most distinguishing feature of turians is their metallic carapace, which contains trace amounts of thulium. The turians evolved this trait as a defense against the greater levels of solar radiation that penetrate their homeworld's weak magnetic field.</p>
                <p>Turian features are avian, making them resemble humanoid birds or raptors. However, unlike most Earth avian creatures, turians are viviparous and give birth to live young.[1] In 2165, David Anderson claimed that turians reminded him of the evolutionary link between birds and dinosaurs. Turians are also recognisable by their voices, which have a distinctive flanging effect. Males and females do not differ greatly in terms of physical appearance, but female turians lack the sweptback cranial crests of their male counterparts and possess larger, cat-like eyes. The lifespan of a turian is comparable to that of a human.</p>
                <p>Turians exhibit the characteristics of predators rather than those of prey species (compare to krogan biology). Their forward-facing alert eyes give the impression that they possess outstanding eyesight and their teeth and jaws mimic the structures possessed by apex predators such as crocodiles or ancient, carnivorous dinosaurs. Their talons on both their feet and hands seem capable of ripping flesh. As such, their diet is primarily meat-based. Their slender bodies also seem to suggest that they are also capable of moving at high speeds.</p>
                <p>The turian homeworld, Palaven, has a metal-poor core, generating a weak magnetic field and allowing more solar radiation into the atmosphere. To deal with this, most forms of life on Palaven evolved some form of metallic "exoskeleton" to protect themselves. Their reflective plate-like carapace makes turians less susceptible to long-term, low-level radiation exposure, but they do not possess any sort of "natural armor". A turian's thick skin does not stop projectiles and directed energy bolts. They can, however, experience the equivalent of a "massage": turians can feel vibrations through the carapace with the use of a hammer.</p>
                <p>Turian blood has a dark blue colouration. Carapace wounds and subsequent scarring may appear red, however.</p>
                <p>Although life on Palaven is carbon-based and oxygen-breathing, it is built on dextro-amino acids. This places the turians in a distinct minority on the galactic stage; the quarians are the only other sapient dextro-protein race. The food of humans, asari, or salarians (who evolved in levo-amino acid-based biospheres), will at best pass through turian systems without providing any nutrition. At worst, it will trigger an allergic reaction that can be fatal if not immediately treated.</p>
                <p>The turian mechanic Lilihierax on Noveria uses the idiom, "if you can polish enough gizzard". This suggests that the turians have a digestive system similar to birds and reptiles on Earth, some of whom swallow stones to help break down harder foods in the stomach.</p>
            </div>
            <br/>
            <div>
                <h1>History</h1>
                <p>Turian civilization spans fifteen thousand years of history. Before the dawn of their civilization, the race was known to elder spacefaring species like the Protheans, who viewed them as primitive as the other ruling races of the modern era.</p>
                <p>As with the other future Council species, the turians have a mass relay within their system. The first turian starship to travel through a relay was called the THV Ravuna.</p>
                <h3>The Unification War</h3>
                <p>The turians had already discovered several mass relays and spawned colonies throughout the galaxy when the asari reached the Citadel. At about the time the asari were forming the Council with the salarians, the turians were embroiled in a bitter civil war next door. The Unification War, as it was later named, began with hostilities between the colonies furthest from the turian homeworld, Palaven.</p>
                <p>These colonies were run by local chieftains, many of whom had distanced themselves from the Hierarchy. Without the galvanizing influence of the government, the colonies became increasingly isolated and xenophobic. Colonists began wearing emblems or facial markings to differentiate themselves from members of other colonies and open hostilities became common.</p>
                <p>When war finally broke out, the Hierarchy maintained strict diplomacy and refused to get involved. After several years of fighting, less than a dozen factions remained and the Hierarchy finally intervened. By that time, the chieftains were too weak to resist; they were forced to put an end to fighting and renew their allegiance to the Hierarchy. Though peace was restored, it took several decades for animosity between colonists to fade completely. To this day, most turians still wear the facial markings of their home colonies.</p>
                <h3>The Krogan Rebellions</h3>
                <p>In the midst of the Krogan Rebellions, the Citadel Council made first contact with the turians. At the Council's behest, the turians brought their considerable war machine to bear on the krogan, now a recognized threat. While the initial turian offensive was successful in routing many krogan warrior bands, it provoked a massive counterattack from the krogan which devastated several turian colonies. Three turian worlds were rendered completely uninhabitable after the krogan used fusion torches to throw asteroids at them, and the bloodiest battle in turian history occurred at Digeris, where the planet was severely bombarded and the turians sacrificed many frigates and fighters to take out a fleet of krogan dreadnoughts. Rather than scaring off the turians with this show of force, the turians only fought with more resolve to quash the krogan utterly. Eventually, the turians implemented the salarian-developed genophage. With their advantage in numbers removed, the majority of krogan were subdued by 800 CE, although scattered insurgent actions would continue for decades.</p>
                <p>By 900 CE, the turians were granted full membership on the Citadel Council in gratitude for their service during the Krogan Rebellions. The turian military fills the military and peacekeeping niche left by the decimated krogan.</p>
                <h3>The Reaper War</h3>
                <p>During the Reaper invasion in 2186, the turian colony of Taetrus is one of the first worlds the Reapers attack following their conquest of Khar'shan and Earth. The Turian Hierarchy made two attempts to liberate Taetrus, but were unsuccessful. As the Reapers began to pour into the Trebia system and assault Palaven, they broadcasted images of Taetrus's destruction to the turian comm buoy network.</p>
                <p>The Reapers met with heavy resistance from the turians during their invasion of Palaven and Menae; much of the turian fleet remained operable after the Reapers' initial assault, and the turian citizenry was heavily armed and capable of supporting turian troops. Although the Hierarchy maintained that Palaven had not fallen and the battle for it continued, the Reapers nonetheless made significant gains and turian casualties rapidly mounted.</p>
                <p>Relief came with the help of an unlikely ally: the krogan, who had agreed to join the war once the genophage was cured. The combined turian and krogan counterattack caught the Reapers off-guard. While the Reaper fleet orbiting Palaven was distracted by an apparent turian offensive, transport craft carrying krogan reinforcements landed on Palaven and coordinated with turian resistance forces, handing over warp bombs and fission weapons. These weapons were smuggled aboard Reaper ships and detonated simultaneously across the globe, allowing large swathes of territory to be retaken. News of the victory gave a much-needed boost to the morale of the turian resistance and the galactic public, but it was not long before the Reapers retaliated.</p>
                <p>Realizing the hopelessness of the situation, Primarch Victus ordered the remaining turian warships to withdraw from the Trebia system in order to participate in the Allied assault on Earth. The only way to end the war was to activate the Crucible, and doing so required the Citadel, which the Reapers had moved to Earth orbit for safekeeping. Turian forces heroically assisted in the space and ground battles, while Commander Shepard reached the Citadel to trigger the Crucible.</p>
            </div>
            <br/>
            <div>
                <h1>Government</h1>
                <p>The turian government, known as the Turian Hierarchy, is a hierarchical meritocracy. While it has great potential for misuse, this is tempered by the civic duty and personal responsibility turians learn during their childhood.</p>
                <p>Turians have 27 citizenship tiers, beginning with civilians (client races and children). The initial period of military service is the second tier. Formal citizenship is conferred at the third tier, after boot camp. For client races, citizenship is granted after the individual musters out. Higher-ranked citizens are expected to lead and protect subordinates. Lower-ranking citizens are expected to obey and support superiors. Promotion to another tier of citizenship is based on the personal assessment of one's superiors and co-rankers. At the top are the Primarchs, who each rule a colonization cluster. The Primarchs vote on matters of national importance. They otherwise maintain a "hands-off" policy, trusting the citizens on each level below them to do their jobs competently.</p>
                <p>Throughout their lives, turians ascend to the higher tiers and are occasionally "demoted" to lower ones. The stigma associated with demotion lies not on the individual, but on those who promoted them when they weren't ready for additional responsibility. This curbs the tendency to promote individuals into positions beyond their capabilities. Settling into a role and rank is not considered stagnation. Turians value knowing one's own limitations more than being ambitious.</p>
                <p>Turians enjoy broad freedoms. So long as one completes their duties, and does not prevent others from completing theirs, nothing is forbidden. For example, there are no laws against recreational drug use, but if someone is unable to complete their duties due to drug use, their superiors step in. Judicial proceedings are 'interventions.' Peers express their concern, and try to convince the offender to change. If rehabilitation fails, turians have no qualms about sentencing dangerous individuals to life at hard labor for the state.</p>
                <p>The turian imperial anthem is called "Die for the Cause."</p>
            </div>
        </div>
    );
}

export default TurianBlog;